Repository vtexdocs/devportal, pull requests merged in 2022-08, with the labels that each got.

#60 Fix/release style
  src/components/release-note/functions.tsx
  src/components/release-note/index.tsx
  src/components/release-note/styles.ts
  src/components/release-section/functions.tsx
  src/components/release-section/index.tsx
  src/components/release-section/styles.tsx
  src/messages/language.json
  src/utils/constants.ts
Labels: release-minor

#63 Feature/On this page
  src/components/contributors/index.tsx
  src/components/contributors/styles.ts
  src/components/icons/close-icon.tsx
  src/components/icons/menu-icon.tsx
  src/components/on-this-page/index.tsx
  src/components/on-this-page/styles.ts
  src/components/table-of-contents/index.tsx
  src/components/table-of-contents/styles.ts
  src/messages/language.json
  src/pages/docs/api-guides/[slug].tsx
  src/styles/documentation-page.ts
  src/utils/contexts/api-guide.tsx
Labels: release-minor

#64 Fix/sidebar structure
  src/components/icons/close-filter-icon.tsx
  src/components/method-category/functions.ts
  src/components/method-category/index.tsx
  src/components/method-category/styles.ts
  src/components/sidebar-elements/index.tsx
  src/components/sidebar-elements/styles.ts
  src/components/sidebar-section-filter/index.tsx
  src/components/sidebar-section-filter/styles.ts
  src/components/sidebar-section/index.tsx
  src/components/sidebar-section/styles.ts
  src/components/sidebar/index.tsx
  src/messages/language.json
  src/pages/docs/api-reference/index.tsx
  src/styles/api-reference.ts
Labels: release-minor

#65 build(rapidoc): update version
  package.json
Labels: release-patch

#61 refactor: switch from Rapidoc to Rapidoc-mini
  src/pages/docs/api-reference/[slug].tsx
  src/tests/cypress/integration/catalog-API-page.spec.js
  src/tests/cypress/support/commands.js
  src/utils/typings/typings.d.ts
Labels: release-minor

#66 Refactor/mdx
  .github/workflows/cypress.yml
  .github/workflows/lighthouse-desktop.yml
  .github/workflows/lighthouse-mobile.yml
  next.config.js
  package.json
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/index.tsx
  src/pages/docs/api-guides/[slug].tsx
  src/utils/string-utils.ts
  yarn.lock
Labels: release-auto

#70 Feature/navigation api
  next.config.js
  package.json
  src/components/sidebar/index.tsx
  src/pages/api/navigation.ts
  src/pages/docs/api-guides/[slug].tsx
  src/pages/docs/api-guides/index.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/api-reference/index.tsx
  src/pages/docs/vtex-io/index.tsx
  src/utils/contexts/sidebar.tsx
  src/utils/getNavigation.ts
  src/utils/hooks/useNavigation.ts
  yarn.lock
Labels: release-minor

#71 Feature/layout
  src/components/layout.tsx
  src/components/sidebar/index.tsx
  src/pages/_app.tsx
  src/pages/docs/api-guides/[slug].tsx
  src/pages/docs/api-guides/index.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/api-reference/index.tsx
  src/pages/docs/vtex-io/index.tsx
Labels: release-auto

#69 Style/header consider modal
  package.json
  src/components/header/index.tsx
Labels: release-auto
