Repository vtexdocs/devportal, pull requests merged in 2022-12, with the labels that each got.

#95 feat(images): compiler gets image data before compiling and generates blured placeholder
  next.config.js
  package.json
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/pages/docs/api-guides/[slug].tsx
  src/utils/remark_plugins/plaiceholder.tsx
  yarn.lock
Labels: release-auto

#92 feat(devportal-scraper): add scraper action and command to run locally
  .github/workflows/docsearch-scraper.yml
  .gitignore
  algolia/scraper_md.json
  algolia/scraper_openapi.json
  algolia/scripts/scraper.sh
  package.json
Labels: release-minor

#93 Feature/Parameters Magic Blocks in Markdown
  src/components/overview-card/index.tsx
  src/utils/replaceMagicBlocks.ts
  src/utils/string-utils.ts
Labels: release-minor

#96 Feat/image remark plugin
  src/components/markdown-renderer/components.tsx
  src/pages/docs/api-guides/[slug].tsx
  src/utils/getGithubFile.ts
  src/utils/remark_plugins/plaiceholder.tsx
Labels: release-auto

#97 Feat/proxy
  CHANGELOG.md
  package-lock.json
  package.json
  src/pages/api/proxy/[url].ts
  yarn.lock
Labels: release-auto

#98 fix(package.json): updates confliting packages
  package.json
  yarn.lock
Labels: release-patch

#100 Build/rapidoc magic blocks
  package.json
  public/docs/api-reference/catalog.json
Labels: release-auto

#101 build(rapidoc): update rapidoc version
  package.json
Labels: release-auto

#103 feat(sitemap): add sitemap for guides-type articles
  algolia/scraper_md.json
  next-sitemap.config.js
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/pages/docs/api-guides/[slug].tsx
  yarn.lock
Labels: release-minor

#102 fix(search-input): change absolute url to relative url
  src/components/search-input/functions.ts
  src/components/search-input/results-box.tsx
Labels: release-patch

#94 feat: add sectionselected
  package.json
  src/components/layout.tsx
  src/components/sidebar-elements/index.tsx
  src/components/sidebar/index.tsx
  src/pages/_app.tsx
  src/pages/docs/api-guides/[slug].tsx
  src/pages/docs/api-guides/index.tsx
  src/pages/docs/vtex-io/index.tsx
  src/utils/contexts/sidebar.tsx
  src/utils/getDocsList.preval.ts
  src/utils/getDocsPaths.ts
Labels: release-patch

#107 fix(escapecurlybraces): pass frontmatter to newContent
  src/utils/escapeCurlyBraces.ts
Labels: release-patch

#111 fix(sidebar-elements): use href
  src/components/sidebar-elements/index.tsx
  src/components/sidebar/index.tsx
Labels: release-patch

#112 Fix/contributors component
  package-lock.json
  src/components/contributors/index.tsx
  src/components/contributors/styles.ts
  src/pages/docs/api-guides/[slug].tsx
  src/utils/getFileContributors.ts
  yarn.lock
Labels: release-minor

#110 Feat/api reference navigation
  package.json
  public/docs/api-reference/Catalog-API.json
  public/docs/api-reference/Checkout-API.json
  public/docs/api-reference/antifraud-provider-protocol-overview.json
  public/navigation.json
  src/components/sidebar-elements/index.tsx
  src/components/sidebar-section/index.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/api-reference/index.tsx
Labels: release-minor

#108 build(rapidoc): update rapidoc version
  package.json
Labels: release-auto

#114 fix(tableo of contents): use getHeadings plugin to populate the headi…
  src/pages/docs/api-guides/[slug].tsx
  src/utils/getHeadings.ts
Labels: release-patch

#118 feat(references): all references being downloaded from github via jsd…
  src/pages/docs/api-reference/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-minor

#116 build(package): update rapidoc version
  package.json
Labels: release-auto

#119 Feat/api-references-page
  src/components/method-category/functions.ts
  src/components/sidebar-elements/index.tsx
  src/components/sidebar/index.tsx
  src/utils/contexts/sidebar.tsx
Labels: release-patch

#120 feat(api-reference): update the API Reference page with cards
  public/images/api-reference.png
  src/pages/docs/api-reference/index.tsx
  src/styles/api-reference.ts
Labels: release-patch

#117 feat(breadcrumb): add breadcrumb component to api-guides
  src/components/breadcrumb/index.tsx
  src/components/breadcrumb/styles.ts
  src/pages/docs/api-guides/[slug].tsx
Labels: release-patch

#123 Fix/Last Breakpoint
  src/components/breadcrumb/index.tsx
  src/components/breadcrumb/styles.ts
  src/components/category-layout/index.tsx
  src/components/category-layout/styles.module.css
  src/components/category-layout/styles.ts
  src/components/contributors/styles.ts
  src/components/documentation-card/functions.ts
  src/components/documentation-card/styles.ts
  src/components/feedback-section/index.tsx
  src/components/feedback-section/styles.ts
  src/components/markdown-renderer/index.tsx
  src/components/see-also-section/styles.ts
  src/components/table-of-contents/styles.ts
  src/pages/docs/api-guides/[slug].tsx
  src/styles/documentation-page.ts
Labels: release-patch

#121 build(package): update rapidoc version
  package.json
Labels: release-auto

#126 feat(sidebar): sidebar element now uses recursive function instead of…
  src/components/sidebar-elements/index.tsx
Labels: release-no

#125 build(package): update rapidoc version
  package.json
Labels: release-auto

#124 fix(search-results): fix title choice to render, remove search page l…
  src/components/search-input/results-box.tsx
  src/components/search-input/styles.ts
Labels: release-minor

#128 feat(sidebar): correct href generation
  src/components/sidebar-elements/index.tsx
Labels: release-no

#106 docs(pages/docs/legacy-cms): add Legacy CMS page
  src/components/icons/legacy-cms-icon.tsx
  src/messages/language.json
  src/pages/docs/legacy-cms/index.tsx
  src/utils/constants.ts
  src/utils/typings/unionTypes.ts
Labels: release-no

#89 feat: treat callout (info, warning, danger, success)
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/pages/docs/api-guides/[slug].tsx
  src/pages/docs/api-guides/rehypeBlockquote.js
  src/styles/global.css
  src/utils/replaceMagicBlocks.ts
Labels: release-patch

#109 docs(releasepage): enable Release Notes section
  src/components/release-note/index.tsx
  src/pages/updates/release-notes/[slug].tsx
  src/pages/updates/release-notes/index.tsx
  src/styles/documentation-page.ts
Labels: release-no

#130 fix(scraper): openapi scraping
  .github/workflows/docsearch-scraper.yml
  algolia/scraper_md.json
  algolia/scraper_openapi.json
  algolia/scripts/scraper.sh
  package.json
  public/sitemap-0.xml
Labels: release-minor

#131 fix(search-input): index name
  algolia/scraper_md.json
  algolia/scraper_openapi.json
  public/sitemap-0.xml
  src/components/search-input/index.tsx
Labels: release-minor

#132 Fix/search index
  .gitignore
  algolia/scripts/scraper.sh
Labels: release-minor

#134 chore(api-guides): use guides instead of api-guides
  algolia/scraper_md.json
  next.config.js
  src/components/last-updates-card/functions.ts
  src/components/last-updates-section/index.tsx
  src/components/release-note/styles.ts
  src/messages/language.json
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/highlightjs-curl.d.ts
  src/pages/docs/guides/index.tsx
  src/pages/docs/guides/rehypeBlockquote.js
  src/pages/docs/storefront-development/index.tsx
  src/pages/docs/vtex-io-apps/index.tsx
  src/utils/constants.ts
  src/utils/typings/unionTypes.ts
Labels: release-no

#137 chore(pages): use main branch from dev-portal-content
  src/pages/docs/guides/[slug].tsx
  src/pages/updates/release-notes/[slug].tsx
  src/utils/getDocsList.preval.ts
  src/utils/getDocsPaths.ts
  src/utils/getReleasePaths.ts
Labels: release-no

#139 feat(release-notes): feat release notes page
  src/components/release-note/index.tsx
  src/components/release-section/index.tsx
  src/pages/updates/release-notes/[slug].tsx
  src/pages/updates/release-notes/index.tsx
  src/styles/documentation-page.ts
  src/utils/constants.ts
  src/utils/getReleasesData.ts
Labels: release-patch

#140 chore(pages): add head, fix css and populate hamburger menu
  src/components/documentation-card/functions.ts
  src/components/documentation-card/index.tsx
  src/components/feedback-section/index.tsx
  src/components/header/hamburger-menu.tsx
  src/components/header/styles.ts
  src/messages/language.json
  src/pages/docs/api-reference/index.tsx
  src/pages/docs/app-development/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/index.tsx
  src/pages/docs/storefront-development/index.tsx
  src/pages/docs/vtex-io-apps/index.tsx
  src/pages/updates/release-notes/[slug].tsx
  src/pages/updates/release-notes/index.tsx
  src/styles/documentation-page.ts
Labels: release-minor
