Repository vtexdocs/devportal, pull requests merged in 2022-11, with the labels that each got.

#84 Feature/algolia search
  package-lock.json
  package.json
  src/components/header/index.tsx
  src/components/header/styles.ts
  src/components/search-input/functions.ts
  src/components/search-input/index.tsx
  src/components/search-input/results-box.tsx
  src/components/search-input/search-box.tsx
  src/components/search-input/styles.ts
  src/pages/docs/api-guides/[slug].tsx
  src/pages/docs/api-reference/[slug].tsx
  src/tests/cypress/integration/landing-page.spec.js
  yarn.lock
Labels: release-minor

#87 fix: implement handleclick and slugprefix
  src/components/sidebar-elements/index.tsx
  src/components/sidebar-section/index.tsx
  src/utils/typings/unionTypes.ts
Labels: release-patch

#91 Use image component
  next.config.js
  package-lock.json
  package.json
  src/components/documentation-card/index.tsx
  src/components/documentation-section-card/index.tsx
  src/components/education-channel/index.tsx
  src/components/header/index.tsx
  src/components/last-updates-card/index.tsx
  src/components/markdown-renderer/components.tsx
  src/components/newsletter-section/index.tsx
  src/components/release-note/index.tsx
  src/components/search-input/results-box.tsx
  src/components/sidebar/index.tsx
  src/components/table-of-contents/index.tsx
  src/components/whats-next-card/index.tsx
  src/pages/docs/api-guides/index.tsx
  src/pages/docs/api-reference/index.tsx
  src/pages/docs/vtex-io/index.tsx
  yarn.lock
Labels: release-auto

#81 Feature/HTML Magic Blocks in Markdown
  src/pages/api/docs.ts
  src/pages/docs/api-guides/[slug].tsx
  src/utils/escapeCurlyBraces.ts
  src/utils/getDocsPaths.ts
  src/utils/replaceHTMLBlocks.ts
  src/utils/replaceMagicBlocks.ts
  src/utils/string-utils.ts
Labels: release-minor

#88 feat: (wip) new comps for getting started page
  src/components/category-layout/index.tsx
  src/components/category-layout/styles.module.css
  src/components/icons/added-icon.tsx
  src/components/icons/close-icon.tsx
  src/components/icons/fixed-icon.tsx
  src/components/icons/improved-icon.tsx
  src/components/icons/menu-icon.tsx
  src/components/icons/removed-icon.tsx
  src/components/icons/vtex-devportal-icon.tsx
  src/components/overview-card/icons.tsx
  src/components/overview-card/index.tsx
  src/components/overview-card/styles.module.css
  src/components/sidebar-elements/functions.tsx
  src/components/sidebar-section/styles.ts
  src/components/sidebar/styles.ts
  src/components/youtube-frame/index.tsx
  src/pages/docs/api-guides/index.tsx
  src/pages/docs/api-guides/styles.module.css
Labels: release-patch
