Repository vtexdocs/devportal, pull requests merged in 2023-06, with the labels that each got.

#390 Update navigation.json
  public/navigation.json
Labels: release-no

#394 Update sidebar: New Release Note for Extensions Hub
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#395 docs(redirects): redirecting data privacy article to new correct slug
  netlify.toml
Labels: release-patch

#396 docs(netlify.toml): fixing pii article redirect
  netlify.toml
Labels: release-patch

#376 docs(navigation): add troubleshooting category and first guide
  public/navigation.json
Labels: release-patch

#399 Fix/mermaid
  src/components/markdown-renderer/components.tsx
  src/pages/_app.tsx
  src/styles/mermaid.css
  src/utils/mermaidInit.ts
Labels: release-patch

#400 Update navigation.json
  public/navigation.json
Labels: release-no

#403 Feature/markdown preview
  package.json
  src/components/copy-button/index.tsx
  src/components/icons/resize-icon.tsx
  src/components/markdown-renderer/components.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/editor/markdown-preview.tsx
  src/pages/updates/release-notes/[slug].tsx
  src/styles/document-editor.ts
  src/utils/escapeCurlyBraces.ts
  src/utils/remark_plugins/client-image.tsx
  src/utils/remark_plugins/rehypeBlockquote.js
  yarn.lock
Labels: release-no

#406 feat(dropwdown-menu): different menu for admin pages
  src/components/documentation-card/index.tsx
  src/components/dropdown-menu/index.tsx
  src/components/header/index.tsx
  src/components/icons/menu-icon.tsx
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/editor/api-index.tsx
  src/pages/editor/markdown-preview.tsx
  src/pages/editor/sidebar.tsx
  src/styles/document-editor.ts
  src/utils/constants.ts
  src/utils/typings/types.ts
  src/utils/typings/unionTypes.ts
Labels: release-auto

#393 EDU-9476 New endpoint Get matcher information settings
  public/navigation.json
Labels: documentation, release-no

#409 Fix/get reference paths
  src/pages/docs/api-reference/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-patch

#411 docs(navigation): add promotions api endpoint
  public/navigation.json
Labels: release-no

#408 Update navigation to new Sales App
  public/navigation.json
Labels: release-no

#407 Preview API Endpoint Auth
  src/pages/api/preview.ts
Labels: release-patch
