Repository vtexdocs/devportal, pull requests merged in 2023-04, with the labels that each got.

#318 docs(navigation): update catalog api menu
  public/navigation.json
Labels: release-no

#312 Feat/Tests
  .github/workflows/cypress-extensive.yml
  .github/workflows/cypress.yml
  cypress.config.mjs
Labels: release-no

#316 docs(navigation): adding navigation for new pick and pack docs
  public/navigation.json
Labels: release-no

#322 Add new endpoint "Handle Cart Items" and sidebar reorganization
  public/navigation.json
Labels: release-no

#321 Orders mdv2 entity breaking change - Release note - Navigation
  public/navigation.json
Labels: release-patch

#315 docs: update navigation.json
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#328 feat(pages): update searchable attributes
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/updates/release-notes/[slug].tsx
  src/utils/typings/unionTypes.ts
Labels: release-no

#326 docs (navigation): fix promotions and taxes v2
  public/navigation.json
Labels: release-no

#324 docs: fixing redirects and navigations according to KR 23Q2-KR1
  netlify.toml
  public/navigation.json
Labels: release-no

#317 docs(adding missing api ref): adds new cards with missing api ref and…
  src/pages/docs/api-reference/index.tsx
Labels: release-no

#333 Add Checkout error codes guide to the sidebar
  public/navigation.json
Labels: release-no

#334 chore(navigation.json): update vtex io apps sidebar
  netlify.toml
  public/navigation.json
Labels: release-no

#332 feat: create api ref index generator tool
  package-lock.json
  src/components/JsonEditorIndex/index.tsx
  src/components/JsonEditorIndex/styles.ts
  src/pages/editor/api-index.tsx
  yarn.lock
Labels: release-auto

#337 Chore/update vtex io apps page
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/vtex-io-apps/index.tsx
Labels: release-auto

#338 fix(guides): fix activeslug
  src/pages/docs/guides/[slug].tsx
Labels: release-no

#320 docs(redirect for pricing hub): redirected 404 link for pricing hub A…
  netlify.toml
Labels: release-no

#342 chore(package.json): update next version
  package.json
  yarn.lock
Labels: release-no

#346 chore(navigation.json): remove beta label from faststore link
  public/navigation.json
Labels: release-no

#344 redirect subscriptions
  netlify.toml
Labels: release-no

#349 refactor(announcementbar): changes the code of announcement bar to hi…
  src/components/header/index.tsx
Labels: release-no

#314 Feat/mermaidjs diagram
  package.json
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/pages/_app.tsx
  src/pages/docs/guides/[slug].tsx
  src/styles/mermaid.css
  src/utils/remark_plugins/mermaid.js
Labels: release-minor

#348 updated file title on navigation.json
  public/navigation.json
Labels: release-no

#330 fix(api-reference): retrieve missing title and description from reference pages
  src/pages/docs/api-reference/[slug].tsx
Labels: release-no

#313 Feat/Lighthouse
  .github/workflows/cypress.yml
  .github/workflows/lighthouse-desktop.yml
  lighthouserc.json
  package.json
  src/tests/cypress/integration/documentation-pages-status.cy.js
  src/tests/cypress/plugins/index.mjs
  src/tests/utils/select-pages.js
  src/tests/utils/summary-report.js
  tsconfig.json
  typings/index.d.ts
  yarn.lock
Labels: release-no

#343 perf(markdown-renderer): remove highlightjs import using head link
  package.json
  src/components/markdown-renderer/index.tsx
  yarn.lock
Labels: release-no

#340 fix: don't send feedback if it's a test
  src/pages/api/feedback.ts
  src/tests/cypress/integration/api-guides.cy.js
Labels: release-patch

#354 chore(navigation.json): fixes navigation slugs
  public/navigation.json
Labels: release-no

#353 updated a file title on navigation.json
  public/navigation.json
Labels: release-no

#351 docs(navigation.json): added new release note to navigation
  public/navigation.json
Labels: release-no

#357 feat(sidebar): support different openapi specs in the same category
  src/components/sidebar/index.tsx
  src/utils/navigation-utils.ts
Labels: release-auto
