Repository vtexdocs/devportal, pull requests merged in 2023-02, with the labels that each got.

#194 build(package): update rapidoc version
  package.json
Labels: release-no

#193 Feat/search filter
  src/components/search-filter-tab-bar/index.tsx
  src/components/search-filter-tab-bar/styles.ts
  src/components/search-input/results-box.tsx
  src/components/search-input/styles.ts
  src/components/search-results/styles.ts
  src/components/search-sections/styles.ts
  src/pages/search/index.tsx
  src/styles/search-page.ts
Labels: release-no

#214 chore(navigation): update navigation file and copy of the app develop…
  public/navigation.json
  src/messages/language.json
  src/utils/constants.ts
Labels: release-auto

#212 feat(markdown-renderer): add CodeBlock and CopyButton components
  package.json
  src/components/code-block/index.tsx
  src/components/code-block/styles.ts
  src/components/copy-button/index.tsx
  src/components/copy-button/styles.ts
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/styles/global.css
Labels: release-auto

#216 Adding subscriptions v2 to navigation
  public/navigation.json
Labels: documentation, release-no

#218 fix navigation subscriptions v2
  public/navigation.json
Labels: documentation, release-no

#219 feat(method-category): enable patch filtering, improve callout style …
  public/navigation.json
  src/components/last-updates-section/index.tsx
  src/components/markdown-renderer/styles.module.css
  src/components/method-category/functions.ts
  src/components/sidebar-section/index.tsx
  src/utils/typings/unionTypes.ts
Labels: release-auto

#217 feat(article-pagination): add Next and Previous page links to guides
  src/components/article-pagination/index.tsx
  src/components/article-pagination/styles.ts
  src/components/feedback-section/styles.ts
  src/pages/docs/guides/[slug].tsx
Labels: release-auto

#220 fix(article-pagination): fix styles and other accessibility issues
  public/navigation.json
  src/components/announcement-bar/index.tsx
  src/components/announcement-bar/styles.ts
  src/components/article-pagination/index.tsx
  src/components/article-pagination/styles.ts
  src/components/breadcrumb/styles.ts
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/components/whats-next-card/styles.ts
  src/pages/docs/guides/[slug].tsx
  src/styles/documentation-page.ts
Labels: release-auto

#221 style(sidebar-elements): fix maxwidth
  src/components/sidebar-elements/styles.ts
  src/pages/updates/release-notes/[slug].tsx
Labels: release-auto

#222 refactor(sidebar): rewrite sidebar functions
  src/components/layout.tsx
  src/components/sidebar/index.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_app.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/index.tsx
  src/pages/updates/release-notes/[slug].tsx
  src/utils/contexts/sidebar.tsx
  src/utils/navigation-utils.ts
  src/utils/typings/types.ts
Labels: release-auto

#223 Adding guides "List pickup points by location and "Get address by pos…
  public/navigation.json
Labels: release-no

#215 chore: sync rapidoc fork
  package.json
  src/pages/docs/api-reference/[slug].tsx
Labels: release-no

#226 fix(components): improve accessibility
  next.config.js
  public/images/meta-image.png
  src/components/article-pagination/styles.ts
  src/components/header/index.tsx
  src/components/header/styles.ts
  src/components/markdown-renderer/styles.module.css
  src/components/sidebar-elements/index.tsx
  src/components/sidebar/index.tsx
  src/pages/_app.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/index.tsx
  src/styles/documentation-page.ts
Labels: release-auto

#225 build: update rapidoc version to add language selection
  package.json
Labels: release-auto

#228 Create redirect - Checkout overview
  next.config.js
Labels: release-no

#229 feat(apps): fetches vtex io apps documentation
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/styles/apps-page.ts
  src/utils/getAppReadme.ts
  src/utils/getChildDocApp.ts
Labels: release-auto

#232 style(styles): update table font-size
  src/components/markdown-renderer/components.tsx
  src/styles/global.css
Labels: release-auto

#224 Fix/doc meta description
  package.json
  src/pages/docs/api-reference/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#234 docs: adding new release note to navigation
  public/navigation.json
Labels: documentation, release-no

#235 chore(navigation): add kit look app release note to navigation.json
  public/navigation.json
Labels: release-no

#236 style(styles): update styles considering the figma file
  src/components/breadcrumb/styles.ts
  src/components/code-block/styles.ts
  src/components/markdown-renderer/styles.module.css
  src/styles/documentation-page.ts
  src/styles/global.css
Labels: release-no

#237 Correct path logistics endpoints
  public/navigation.json
Labels: release-no

#239 Add "Create a regular order from an existing cart" reference to sidebar
  public/navigation.json
Labels: release-no

#240 feat(header scripts): add GA script
  src/components/layout.tsx
Labels: release-auto

#233 Navigation and redirect/making your first request/update
  next.config.js
  public/navigation.json
Labels: release-patch

#242 fix(rehypeblockquote): fixes long callouts
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/updates/release-notes/[slug].tsx
  src/utils/remark_plugins/rehypeBlockquote.js
Labels: release-auto

#244 feat(layout): add GTM
  src/components/layout.tsx
Labels: release-no

#245 docs(navigation): edit Catalog, Search and Message Center guides
  public/navigation.json
Labels: release-no

#246 feat(layout): correct GTM
  src/components/layout.tsx
Labels: release-no

#247 fix(overview-card): update overview card
  src/components/overview-card/icons.tsx
  src/components/overview-card/index.tsx
  src/components/overview-card/styles.module.css
  src/components/overview-card/styles.ts
Labels: release-no

#249 Getting started authentication navigation improvements
  next.config.js
  public/navigation.json
Labels: release-patch

#251 docs(navigation): update catalog guides navigation
  next.config.js
  public/navigation.json
Labels: release-no

#248 Feat/mobile menu
  src/components/announcement-bar/styles.ts
  src/components/documentation-card/index.tsx
  src/components/header/hamburger-menu.tsx
  src/components/header/index.tsx
  src/components/header/styles.ts
  src/components/icons/arrow-left-icon.tsx
  src/components/layout.tsx
  src/components/sidebar-section/index.tsx
  src/components/sidebar-section/styles.ts
  src/utils/contexts/sidebar.tsx
Labels: release-minor

#253 Change path authorize fulfillment
  next.config.js
  public/navigation.json
Labels: release-no

#254 remove Add log in orders from navigation
  public/navigation.json
Labels: release-no

#252 Fix/mobile overflow
  src/components/markdown-renderer/styles.module.css
  src/styles/documentation-page.ts
  src/styles/global.css
Labels: release-patch

#255 Update sidebar "Get sellers by region or address"
  public/navigation.json
Labels: release-no

#257 Update sidebar "Fulfillment" and "Region"
  public/navigation.json
Labels: release-no

#259 Feature/algolia analytics
  algolia/scripts/scraper.sh
  package.json
  src/components/search-input/index.tsx
  src/components/search-input/results-box.tsx
Labels: release-no

#256 Feat/Tests
  .github/workflows/cypress.yml
  cypress.config.mjs
  cypress.json
  package.json
  src/tests/cypress/integration/api-guides-documentation.spec.js
  src/tests/cypress/integration/catalog-API-page.spec.js
  src/tests/cypress/integration/documentation-pages-status.cy.js
  src/tests/cypress/integration/landing-page.spec.js
  src/utils/getHeadings.ts
  yarn.lock
Labels: release-no
