Repository vtexdocs/devportal, pull requests merged in 2023-03, with the labels that each got.

#243 New order and fulfillment navigation guides
  public/navigation.json
Labels: release-no

#264 Updated "Create a new cart" endpoint reference
  public/navigation.json
Labels: release-no

#268 docs: delete guide and create redirect
  next.config.js
  public/navigation.json
Labels: release-no

#265 docs(navigation): correct marketplace protocol
  next.config.js
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
  yarn.lock
Labels: release-no

#270 docs: create redirects marketplace protocol
  next.config.js
Labels: release-no

#271 docs(navigation): fix sessions endpoints that have had the paths fixed
  public/navigation.json
Labels: release-patch

#262 Feat/fixed sidebar
  src/components/documentation-card/index.tsx
  src/components/header/hamburger-menu.tsx
  src/components/header/styles.ts
  src/components/sidebar-section/index.tsx
  src/components/sidebar-section/styles.ts
  src/components/sidebar/styles.ts
Labels: release-patch

#266 Feat/download spec
  package.json
  src/pages/docs/api-reference/[slug].tsx
Labels: release-auto

#273 redirect 2
  next.config.js
Labels: release-no

#275 Fix/responsive design
  src/components/sidebar-section/index.tsx
  src/styles/documentation-page.ts
Labels: release-patch

#276 docs(navigation): add new intelligent search guides
  public/navigation.json
Labels: release-no

#278 Add PSE Payment Method - Payment Integration Guide
  public/navigation.json
Labels: release-no

#279 Update Release Note position - PSE: Payment method
  public/navigation.json
Labels: release-no

#277 Feat/lightbox
  src/components/contributors/index.tsx
  src/components/header/hamburger-menu.tsx
  src/components/icons/close-icon.tsx
  src/components/lightbox/index.tsx
  src/components/lightbox/styles.ts
  src/components/markdown-renderer/components.tsx
  src/components/see-also-section/index.tsx
Labels: release-minor

#280 Top bar update: persona research
  src/components/header/index.tsx
Labels: release-patch

#281 build(package): update rapidoc version
  package.json
Labels: release-no

#283 fix: handle image loading errors
  src/components/markdown-renderer/components.tsx
  src/messages/language.json
Labels: release-patch

#285 feat(editor): v1 of sidebar editor
  public/images/editor.png
  src/components/JsonEditorComponent/index.tsx
  src/components/JsonEditorComponent/styles.ts
  src/components/layout.tsx
  src/components/sidebar-elements/index.tsx
  src/components/sidebar-section/index.tsx
  src/components/sidebar-section/styles.ts
  src/components/sidebar/index.tsx
  src/pages/_app.tsx
  src/pages/editor/sidebar.tsx
  src/utils/contexts/sidebar.tsx
  src/utils/typings/types.ts
Labels: release-auto

#287 feat(editor): add toast feedback to json editor
  package.json
  src/components/JsonEditorComponent/index.tsx
  src/components/JsonEditorComponent/styles.ts
Labels: release-patch

#291 docs(navigation): fix position of catalog guide
  public/navigation.json
Labels: release-no

#289 fix(sidebar): check the parent to expand the correct endpoint
  src/components/sidebar/index.tsx
  src/utils/navigation-utils.ts
Labels: release-patch

#292 feat(preview): enable preview mode
  src/components/announcement-bar/index.tsx
  src/components/announcement-bar/styles.ts
  src/components/header/index.tsx
  src/pages/api/disable-preview.ts
  src/pages/api/preview.ts
  src/pages/docs/guides/[slug].tsx
  src/utils/getDocsPaths.ts
Labels: release-minor

#293 Feat/get branch name
  src/components/announcement-bar/index.tsx
  src/components/header/index.tsx
  src/components/layout.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_app.tsx
  src/pages/docs/app-development/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/index.tsx
  src/pages/docs/storefront-development/index.tsx
  src/pages/docs/vtex-io-apps/index.tsx
  src/pages/index.tsx
  src/pages/updates/release-notes/[slug].tsx
  src/pages/updates/release-notes/index.tsx
  src/utils/contexts/preview.tsx
  src/utils/getReleasePaths.ts
  src/utils/getReleasesData.ts
Labels: release-minor

#267 Feat/Tests
  .github/workflows/cypress.yml
  cypress.config.mjs
  src/pages/docs/guides/[slug].tsx
  src/pages/updates/release-notes/[slug].tsx
  src/tests/cypress/integration/documentation-pages-status.cy.js
  src/utils/getReleasesData.ts
Labels: release-no

#295 chore(tracker): update tracker
  package.json
  yarn.lock
Labels: release-no

#288 Feature/e2e-tests
  .gitignore
  cypress.config.mjs
  package.json
  src/components/contributors/index.tsx
  src/components/feedback-modal/index.tsx
  src/components/feedback-section/index.tsx
  src/components/sidebar-elements/index.tsx
  src/components/sidebar-section/index.tsx
  src/components/sidebar/index.tsx
  src/components/table-of-contents/index.tsx
  src/tests/cypress/integration/api-guides.cy.js
  src/tests/cypress/integration/api-reference.cy.js
  src/tests/cypress/integration/documentation-pages-status.cy.js
  src/tests/cypress/plugins/index.mjs
  src/tests/cypress/support/commands.js
  src/tests/cypress/support/events.js
  src/tests/cypress/support/functions.js
  src/tests/cypress/support/index.js
  tsconfig.json
  yarn.lock
Labels: release-no

#298 Update navigation.json
  public/navigation.json
Labels: release-no

#300 Shipping network api
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#301 docs: changed url in navigation.json
  public/navigation.json
Labels: release-no

#302 refactor(tsconfig): remove unecessary dependencies and change module …
  tsconfig.json
Labels: release-no

#303 refactor(redirects): use netlify redirects
  netlify.toml
  next.config.js
Labels: release-no

#304 fix(tsconfig): who would've guessed tsconfig can get this hard
  tsconfig.json
Labels: release-no

#306 Feat/icons overviewcard
  src/components/overview-card/icons.tsx
  src/components/overview-card/index.tsx
Labels: release-no

#307 New redirect Add & handle custom inf in the order
  netlify.toml
Labels: release-no

#297 Feat/Tests Summary Report
  .github/workflows/cypress.yml
  cypress.config.mjs
  src/tests/cypress/integration/api-reference.cy.js
  src/tests/cypress/integration/documentation-pages-status.cy.js
  src/tests/cypress/plugins/index.mjs
  src/tests/cypress/support/index.js
  src/tests/summary-report.js
Labels: release-no

#309 style(rapidoc): update rapidoc version and styles
  package.json
  src/styles/rapidoc.css
Labels: release-no

#310 Styles/pagination
  src/components/article-pagination/index.tsx
  src/components/article-pagination/styles.ts
  src/components/feedback-section/styles.ts
  src/components/icons/edit-icon.tsx
  src/components/lightbox/styles.ts
  src/components/markdown-renderer/styles.module.css
  src/styles/documentation-page.ts
Labels: release-no

#308 Navigation/publish service path guide
  public/navigation.json
Labels: release-patch

#296 Feat/api feedback
  package.json
  sheets-secrets
  src/components/feedback-modal/index.tsx
  src/components/feedback-section/index.tsx
  src/components/lightbox/index.tsx
  src/pages/api/feedback.ts
  src/pages/docs/guides/[slug].tsx
  src/utils/get-variables.ts
  yarn.lock
Labels: release-minor
