Repository vtexdocs/devportal, pull requests merged in 2023-05, with the labels that each got.

#358 Feat/Lighthouse
  .github/workflows/cypress-extensive.yml
  .github/workflows/lighthouse-desktop.yml
Labels: release-no

#359 Update navigation.json
  public/navigation.json
Labels: release-no

#363 Updated sidebar: Deprecation of List Payment Methods endpoint
  public/navigation.json
Labels: release-no

#364 List Payment Provider Manifest endpoint redirect
  netlify.toml
Labels: release-no

#367 Create container-template.json
  public/container-template.json
Labels: release-auto

#366 feat(apps): add Breadcrumbs and Pagination to app pages, among other …
  src/components/article-pagination/index.tsx
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/styles/documentation-page.ts
  src/styles/global.css
Labels: release-no

#368 Update container-template.json
  public/container-template.json
Labels: release-no

#365 Update sidebar: New Release Note for Google Tag Manager
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#369 Update navigation.json
  public/navigation.json
Labels: release-no

#370 Update navigation.json
  public/navigation.json
Labels: release-no

#345 perf: code optimization
  src/components/feedback-section/index.tsx
  src/components/search-input/results-box.tsx
  src/components/sidebar-section/index.tsx
  src/components/tooltip/index.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
Labels: release-minor

#355 fix: nextjs shouldn't optimize image if it is a gif
  src/components/markdown-renderer/components.tsx
Labels: release-patch

#371 perf/remove-sidebar-shift
  .github/workflows/cypress.yml
  cypress.config.mjs
  src/components/sidebar-section/index.tsx
  src/tests/cypress/integration/api-guides.cy.js
  src/tests/cypress/integration/api-reference.cy.js
Labels: release-no

#374 Update netlify.toml
  netlify.toml
Labels: release-no

#331 Feat/search-page
  algolia/scraper_md.json
  algolia/scraper_openapi.json
  src/components/icons/expanded-results-icon.tsx
  src/components/layout.tsx
  src/components/method-category/functions.ts
  src/components/method-category/index.tsx
  src/components/search-card/functions.tsx
  src/components/search-card/index.tsx
  src/components/search-card/styles.ts
  src/components/search-filter-tab-bar/index.tsx
  src/components/search-input/customHighlight.tsx
  src/components/search-input/functions.ts
  src/components/search-input/index.tsx
  src/components/search-input/results-box.tsx
  src/components/search-input/search-box.tsx
  src/components/search-input/styles.ts
  src/components/search-results/customHits.tsx
  src/components/search-results/index.tsx
  src/components/search-results/pagination.tsx
  src/components/search-results/styles.ts
  src/components/search-section/index.tsx
  src/components/search-sections/index.tsx
  src/components/sidebar/index.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/pages/docs/app-development/index.tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/index.tsx
  src/pages/docs/storefront-development/index.tsx
  src/pages/search/index.tsx
  src/tests/cypress/integration/api-guides.cy.js
  src/tests/cypress/integration/api-reference.cy.js
  src/utils/constants.ts
  src/utils/contexts/search.tsx
  src/utils/contexts/sidebar.tsx
  src/utils/search-utils.ts
Labels: release-minor

#375 chore(netlify.toml): add redirect for livestreaming app
  netlify.toml
Labels: release-no

#378 Update container-template.json
  public/container-template.json
Labels: release-no

#379 Chore: redirect Order Form doc
  netlify.toml
Labels: release-no

#380 Chore: fix Order Form redirect
  netlify.toml
Labels: release-no

#385 Feat/Auth
  package.json
  src/components/auth/index.tsx
  src/components/auth/styles.ts
  src/components/sidebar-section/index.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].js
  src/pages/api/preview.ts
  src/pages/editor/api-index.tsx
  src/pages/editor/sidebar.tsx
  typings/index.d.ts
  yarn.lock
Labels: release-minor

#387 Feat/release notes filter
  src/components/icons/checkbox.tsx
  src/components/multiselect/index.tsx
  src/components/multiselect/styles.ts
  src/components/release-section/index.tsx
  src/messages/language.json
  src/pages/updates/release-notes/index.tsx
  src/utils/getActionTypes.ts
  src/utils/typings/types.ts
Labels: release-minor

#388 Fix/search page style
  src/components/search-card/index.tsx
  src/components/search-card/styles.ts
  src/components/search-input/customHighlight.tsx
  src/components/search-input/styles.ts
  src/components/search-results/index.tsx
  src/components/search-results/styles.ts
Labels: release-patch

#381 test(cypress): simplify the test on TOC in guides pages
  src/tests/cypress/integration/api-guides.cy.js
  src/tests/cypress/integration/api-reference.cy.js
Labels: release-no
