Repository vtexdocs/devportal, pull requests merged in 2023-07, with the labels that each got.

#416 docs(navigation): added jun/jul 2023 releases
  public/navigation.json
Labels: release-no

#415 docs: add intelligent search events api headless
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#417 Navigation bar updated
  public/navigation.json
Labels: release-no

#410 Fixed redirect for product-price app
  CHANGELOG.md
  netlify.toml
Labels: release-no

#419 Update navigation.json
  public/navigation.json
Labels: release-no

#418 docs(navigation): add teasers field release notes to navigation
  public/navigation.json
Labels: release-no

#421 docs(navigation): add change in sku notification release notes
  public/navigation.json
Labels: release-no

#420 Add builders application form RN to navigation
  public/navigation.json
Labels: release-no

#422 Update netlify.toml
  netlify.toml
Labels: release-no

#352 chore: update navigation.json
  public/navigation.json
Labels: release-no

#425 docs: create redirect catalog api seller portal
  netlify.toml
Labels: release-no

#414 Hide search card full description
  src/components/search-card/index.tsx
Labels: release-minor

#427 Update navigation.json
  public/navigation.json
Labels: release-no

#429 docs: add redirect
  netlify.toml
Labels: release-no

#435 docs(navigation): edit promotions api
  public/navigation.json
Labels: release-no

#432 EDU-7868 | Navigation marketplace guide
  public/navigation.json
Labels: documentation, release-no

#438 docs(navigation): update erp guide name in nav
  public/navigation.json
Labels: release-no

#439 Update netlify.toml
  netlify.toml
Labels: release-no

#441 style(documentation-page): update content width
  src/styles/documentation-page.ts
Labels: release-no

#442 chore(navigation): updates navigation.json
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#443 Feedback 3088 redirect
  netlify.toml
Labels: release-no

#444 docs: edit-legacy-cms-portal-nav
  netlify.toml
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/pages/api/postman/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#445 docs: update index.tsx
  src/pages/docs/api-reference/index.tsx
Labels: release-no

#448 Update navigation.json
  public/navigation.json
Labels: release-no

#450 Update navigation.json
  public/navigation.json
Labels: release-no

#449 Update navigation.json: New release notes
  public/navigation.json
Labels: release-no
