Repository vtexdocs/devportal, pull requests merged in 2023-01, with the labels that each got.

#141 feat(netlify.toml): add file
  .gitignore
  getPEM.sh
  netlify.toml
  next.config.js
  package.json
  src/utils/config.ts
  yarn.lock
Labels: release-no

#142 Fix/Spacing in Last Breakpoint
  src/components/markdown-renderer/index.tsx
  src/components/table-of-contents/styles.ts
  src/styles/documentation-page.ts
Labels: release-patch

#143 Fix/search input results
  package-lock.json
  src/components/search-input/results-box.tsx
  src/components/search-input/search-box.tsx
  src/components/search-results/index.tsx
  src/messages/language.json
  src/utils/constants.ts
  src/utils/typings/unionTypes.ts
  yarn.lock
Labels: release-minor

#145 fix(config): increse max page data size warning
  next.config.js
Labels: release-auto

#146 build(package): update rapidoc version
  package.json
Labels: release-auto

#152 feat(references): use edge api to get openapis
  src/pages/api/openapi/[slug].tsx
  src/pages/docs/api-reference/[slug].tsx
Labels: release-auto

#151 Fix/Schema Tabs
  package.json
  src/pages/docs/api-reference/[slug].tsx
Labels: release-patch

#156 fix(utils): fix getReleaseData
  src/utils/getReleasesData.ts
Labels: release-minor

#155 fix(newsletter): hiding newsletter subscription
  src/components/newsletter-section/index.tsx
Labels: release-patch

#157 feat(releases): release notes now are built on demand
  .gitignore
  src/pages/updates/release-notes/[slug].tsx
Labels: release-no

#160 fix(sidebar-elements): update the route for openapis without method
  public/navigation.json
  src/components/sidebar-elements/index.tsx
Labels: release-no

#158 fix: add create-a-brand to navigation.json
  public/navigation.json
Labels: release-patch

#162 fix(see-also-section): update functions
  src/components/see-also-section/functions.ts
Labels: release-no

#159 Remove deprecated subscriptions navigation
  public/navigation.json
Labels: release-no

#163 fix(sidebar): open proper sidebar on refresh
  public/navigation.json
  src/components/sidebar-elements/index.tsx
  src/components/sidebar/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/index.tsx
Labels: release-no

#161 Fixing table overflow in API Guide pages
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
Labels: release-patch

#166 style(rapidoc): update rapidoc version
  package.json
  src/styles/rapidoc.css
Labels: release-no

#165 Update navigation.json
  public/navigation.json
Labels: release-no

#169 style(package.json): update rapidoc version
  package.json
  src/styles/rapidoc.css
Labels: release-no

#171 chore(navigation.json): fix slugs
  public/navigation.json
Labels: release-no

#172 fix(slug): update header and rapidoc version
  package.json
  public/navigation.json
  src/styles/rapidoc.css
Labels: release-no

#150 Redirect of Payment Provider Protocol API Overview
  next.config.js
Labels: release-patch

#173 fix(slug): add api header title
  public/navigation.json
  src/components/last-updates-section/index.tsx
  src/pages/docs/api-reference/[slug].tsx
  src/styles/global.css
Labels: release-no

#175 Include navigation fulfillment and subscriptions
  public/navigation.json
Labels: release-no

#176 chore(navigation): update redirects and navigation
  next.config.js
  public/navigation.json
Labels: release-no

#177 chore(navigation): update navigation
  public/navigation.json
Labels: release-no

#179 Added "Cart Attachments" and "Configuration" Sections to sidebar
  public/navigation.json
Labels: release-no

#178 feat(components): export overviewcard and update table styles
  src/components/breadcrumb/styles.ts
  src/components/markdown-renderer/components.tsx
  src/components/markdown-renderer/styles.module.css
  src/components/overview-card/index.tsx
  src/components/whats-next-card/index.tsx
  src/components/whats-next-card/styles.ts
  src/pages/docs/api-reference/index.tsx
  src/pages/docs/storefront-development/index.tsx
  src/pages/docs/vtex-io-apps/index.tsx
  src/styles/documentation-page.ts
  src/styles/global.css
  src/utils/constants.ts
  src/utils/typings/types.ts
Labels: release-no

#174 build: update rapidoc version to have working api requests
  package.json
Labels: release-auto

#153 Fix/Missing Backtick
  src/pages/docs/guides/[slug].tsx
  src/utils/escapeCurlyBraces.ts
Labels: release-patch

#182 fix: add list migration doc to navigation.json
  public/navigation.json
Labels: release-no

#184 removing items from navigation
  public/navigation.json
Labels: release-patch

#149 Feature/server sitemap
  .gitignore
  algolia/scraper_openapi.json
  next-sitemap.config.js
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/pages/server-sitemap.xml/index.ts
Labels: release-minor

#180 Fix/Responsive Design
  src/components/breadcrumb/index.tsx
  src/components/breadcrumb/styles.ts
  src/components/contributors/styles.ts
  src/components/documentation-card/functions.ts
  src/components/documentation-card/index.tsx
  src/components/documentation-card/styles.ts
  src/components/feedback-section/index.tsx
  src/components/feedback-section/styles.ts
  src/components/header/styles.ts
  src/components/page-header/styles.ts
  src/components/release-note/styles.ts
  src/components/release-section/index.tsx
  src/components/release-section/styles.tsx
  src/components/search-results/styles.ts
  src/components/search-sections/styles.ts
  src/components/see-also-section/styles.ts
  src/components/table-of-contents/index.tsx
  src/components/table-of-contents/styles.ts
  src/components/whats-next-card/styles.ts
  src/pages/updates/release-notes/index.tsx
  src/styles/documentation-landing-page.ts
  src/styles/documentation-page.ts
  src/styles/release-notes.ts
  src/styles/search-page.ts
Labels: release-patch

#183 feat(search-input): custom highlighting to search results
  src/components/search-input/customHighlight.tsx
  src/components/search-input/results-box.tsx
  src/components/search-input/styles.ts
Labels: release-minor

#181 fix(blockquote): use trimStart instead of trim
  src/pages/docs/guides/rehypeBlockquote.js
Labels: release-patch

#186 docs: adding navigation release note api breaking change
  public/navigation.json
Labels: release-no

#187 feat(scraper): update scraper config files
  algolia/scraper_md.json
  algolia/scraper_openapi.json
  algolia/scripts/scraper.sh
Labels: release-minor

#189 docs(public/navigation.json): adding SafeData release note to navigation
  public/navigation.json
Labels: release-patch

#191 Correcting reference path map for the Orders API (PII version)
  src/utils/getReferencePaths.ts
Labels: release-patch

#197 fix(navigation): add SKU Service endpoints to navigation.json
  public/navigation.json
Labels: release-no

#198 docs(navigation): add get gift list endpoint
  public/navigation.json
Labels: release-no

#199 build(package): update rapidoc version
  package.json
Labels: release-major

#195 Redirects new and migrated.
  next.config.js
Labels: release-minor

#201 fix(release-version): add token to checkout action
  .github/workflows/release-version.yml
Labels: release-major

#202 fix(global.css): create css classes for http methods
  src/styles/global.css
Labels: release-patch

#203 fix(config): stop worker threads
  next.config.js
Labels: release-no

#204 docs(navigation): edit marketplace api paths
  public/navigation.json
Labels: release-no

#205 docs(navigation): fix marketplace api navigation
  public/navigation.json
Labels: release-no

#185 chore(navigation): update master data v2 overview redirect
  next.config.js
Labels: release-patch

#208 chore(last-updates-section): update hard-coded lastReleaseNote
  src/components/last-updates-section/index.tsx
Labels: release-no

#207 perf(search-input): stop search with an empty query
  src/components/search-input/index.tsx
  src/components/search-input/results-box.tsx
Labels: release-no

#209 docs(navigation): correct vtex id endpoint (generate authentication t…
  public/navigation.json
Labels: release-patch

#210 docs(navigation): correct marketplace api navigation
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
  yarn.lock
Labels: release-no
