Repository vtexdocs/devportal, pull requests merged in 2023-11, with the labels that each got.

#426 feat(codehike): install codehike
  package.json
  src/components/code-block/index.tsx
  src/components/markdown-renderer/components.tsx
  src/pages/_app.tsx
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/updates/release-notes/[slug].tsx
  src/styles/codeHikeTheme.ts
  src/styles/documentation-page.ts
  src/styles/global.css
Labels: release-minor

#520 EDU-11017 - redirect link seller update by seller ID
  netlify.toml
Labels: release-no

#521 Update navigation.json
  public/navigation.json
Labels: release-no

#522 Create redirect after removing beta mention in slug
  netlify.toml
Labels: release-no

#512 test(api-reference): add additional wait to tests in reference page
  src/tests/cypress/integration/api-reference.cy.js
  src/tests/cypress/integration/documentation-pages-status.cy.js
Labels: release-no

#525 chore(navigation.json): add release note to navigation
  public/navigation.json
Labels: release-no

#526 style(release-notes): add info release type + improve styles
  src/components/icons/info-icon.tsx
  src/components/last-updates-card/functions.ts
  src/components/last-updates-section/index.tsx
  src/components/multiselect/styles.ts
  src/components/release-note/functions.tsx
  src/components/release-note/styles.ts
  src/components/release-section/functions.tsx
  src/components/release-section/index.tsx
  src/components/release-section/styles.tsx
  src/pages/updates/release-notes/[slug].tsx
Labels: release-no

#524 Adjust navigation
  public/navigation.json
Labels: documentation, release-no

#528 Update navigation.json
  public/navigation.json
Labels: release-no

#527 chore(navigation.json): update api guides navigation
  public/navigation.json
Labels: release-no

#529 docs: create redirect
  netlify.toml
Labels: release-no
