Repository vtexdocs/devportal, pull requests merged in 2024-06, with the labels that each got.

#656 docs(navigation): add data protection plus guides
  public/navigation.json
Labels: release-no

#670 Getting started with storefront solutions sidebar
  public/navigation.json
Labels: release-no

#671 docs: add VTEX Platform Overview category and docs to navigation | 24H1KR3
  public/navigation.json
Labels: release-no

#673 docs: create redirect to Composability guide
  netlify.toml
Labels: release-no

#674 Adding vtex platform overview release note to navigation.json
  public/navigation.json
Labels: release-no

#675 feat(navigation.json): add fs managing performance
  public/navigation.json
Labels: release-no

#672 docs: create redirect to new platform overview category
  netlify.toml
Labels: release-no

#678 Adding configuring-dynamic-routes-in-vtex-io-services.md to sidebar
  public/navigation.json
Labels: release-no

#679 chore(navigation.json): fix navigation error
  public/navigation.json
Labels: release-no

#677 feat(navigation.json): update faststore overview doc slug
  public/navigation.json
Labels: release-no

#681 chore(faststore/index.tsx): remove unused page
  netlify.toml
  src/pages/docs/guides/faststore/index.tsx
  src/pages/docs/storefront-development/index.tsx
Labels: release-no

#682 docs: fix orders pii api navigation
  public/navigation.json
Labels: release-no

#683 Update navigation.json
  public/navigation.json
Labels: release-no

#684 feat(navigation.json): add fs testing-the-server-side-rendering doc
  public/navigation.json
Labels: release-no

#685 Add composability text with reference to API guides cover
  src/pages/docs/guides/index.tsx
Labels: documentation, release-no

#659 Feat: New troubleshooting page
  netlify.toml
  package.json
  public/images/troubleshooting-image-header.png
  public/navigation.json
  src/components/icons/troubleshooting-icon.tsx
  src/components/pagination/index.tsx
  src/components/pagination/styles.ts
  src/components/see-also-section/functions.ts
  src/components/troubleshooting-card/index.tsx
  src/components/troubleshooting-card/styles.ts
  src/messages/language.json
  src/pages/docs/troubleshooting/[slug].tsx
  src/pages/docs/troubleshooting/index.tsx
  src/utils/constants.ts
  src/utils/getTroubleshootingData.ts
  src/utils/getTroubleshootingPaths.ts
  src/utils/typings/types.ts
  src/utils/typings/unionTypes.ts
Labels: release-minor

#686 fix(navigation.json): troubleshooting sidebar
  public/navigation.json
Labels: release-no

#687 docs(navigation): add troubleshooting modal layout
  public/navigation.json
Labels: release-no

#688 add new endpoints to navigation
  public/navigation.json
Labels: release-no

#689 docs: adding to navigation
  public/navigation.json
Labels: release-no

#676 Adding release note to navigation.json
  public/navigation.json
Labels: release-no

#690 feat(navigation.json): add fs dynamic content
  public/navigation.json
Labels: release-no

#691 feat(navigation.json): add dynamic content release note
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#635 Fix: navigation.json - FastStore WebOps
  public/navigation.json
Labels: release-no

#692 docs: adding dev experience link
  src/pages/docs/app-development/index.tsx
Labels: release-no

#694 EDU-18812 Fixed sidebar Buyer organizations
  public/navigation.json
Labels: release-no

#697 fix(navigation.json): troubleshooting sidebar navigation
  public/navigation.json
Labels: release-no

#703 feat(index.tsx): adding new support component to the troubleshooting page
  public/navigation.json
  src/messages/language.json
  src/pages/docs/troubleshooting/index.tsx
  src/utils/constants.ts
  src/utils/get-url.tsx
  src/utils/typings/types.ts
  src/utils/typings/unionTypes.ts
Labels: release-auto

#661 feat: update navigation.json
  public/navigation.json
Labels: release-no

#700 fix(rehypeblockquote): update extendedNames
  src/utils/remark_plugins/rehypeBlockquote.js
Labels: release-no

#707 fix(faststorecomponents.tsx): fix Tabs behavior
  src/components/faststore-components/markdown-renderer/fastStoreComponents.tsx
Labels: release-no

#708 feat(navigation.json): update troubleshooting sidebar
  public/navigation.json
Labels: release-no

#709 docs(navigation): fix data protection plus guides
  public/navigation.json
Labels: release-no

#711 docs: reorganizing and updating navigation.json
  public/navigation.json
Labels: release-no

#710 feat(navigation.json): add new troubleshooting article
  public/navigation.json
Labels: release-no

#669 feat(navigation.json): update hCMS sidebar
  public/navigation.json
Labels: release-no

#712 feat(navigation.json): add section override use cases
  public/navigation.json
Labels: release-no

#713 feat(storefront-development/index.tsx): adding dev experience link
  src/pages/docs/storefront-development/index.tsx
Labels: release-no
