Repository vtexdocs/devportal, pull requests merged in 2024-03, with the labels that each got.

#603 Fix: create Faststore doc redirect
  netlify.toml
Labels: release-no

#604 docs: create redirects api overviews
  netlify.toml
Labels: release-no

#607 feat: add Checkout Config API
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-minor

#600 chore(netlify.toml): add faststore redirects
  netlify.toml
Labels: release-no

#608 Chore: FastStore release note
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#609 docs(navigation): update master data apis navigation
  public/navigation.json
Labels: release-no

#611 Fix: Integrating the VTEX login slug
  public/navigation.json
Labels: release-no

#612 Update navigation.json
  public/navigation.json
Labels: release-no

#614 Update navigation.json: New doc - Mutiple page templates
  public/navigation.json
Labels: release-no

#616 fix(apps/[slug]): parse markdown value from json
  src/components/faststore-components/Newsletter/NewsletterUsage.tsx
  src/pages/docs/apps/[slug]/index.tsx
Labels: bug, release-no

#613 docs: creating redirects to fix 404 error
  netlify.toml
Labels: release-no

#618 [EDU-11754] Fixed sidebar link
  public/navigation.json
Labels: release-no

#619 chore(netlify.toml): update faststore redirects
  netlify.toml
Labels: release-no

#620 Fix: FastStore navigation.json
  public/navigation.json
Labels: release-no

#622 docs: create redirect
  netlify.toml
Labels: release-no

#621 chore(last-updates-section): update last rn
  src/components/last-updates-section/index.tsx
  src/pages/docs/apps/[slug]/index.tsx
Labels: release-no

#623 docs: create redirect master data guide
  netlify.toml
Labels: release-no
