Repository vtexdocs/devportal, pull requests merged in 2024-05, with the labels that each got.

#641 docs(navigation): fix sidebar link
  public/navigation.json
Labels: release-no

#642 Updating navigation.json
  public/navigation.json
Labels: release-no

#643 chore(package.json): update faststore major
  package.json
Labels: release-auto, dependencies

#644 fix(replacehtmlblocks): close open img tags
  src/utils/replaceHTMLBlocks.ts
Labels: release-no

#645 fix(replacehtmlblocks): consider <img...></img> case
  src/utils/replaceHTMLBlocks.ts
Labels: release-no

#646 Update navigation.json - Section override v2
  public/navigation.json
Labels: release-no

#648 chore(package.json): update components package
  package.json
  src/components/layout.tsx
  src/utils/constants.ts
  src/utils/typings/types.ts
Labels: release-patch

#647 style(faststore.scss): fixes
  package.json
  src/components/faststore-components/CardList/CardItem.tsx
  src/components/faststore-components/CardList/card-list.module.css
  src/components/faststore-components/Icon/icon.module.css
  src/components/faststore-components/OverviewSection/OverviewSection.tsx
  src/components/faststore-components/OverviewSection/overview-section.module.css
  src/components/faststore-components/PropsSection/props-section.module.css
  src/components/faststore-components/SectionItem/SectionItem.tsx
  src/components/faststore-components/SectionItem/section-item.module.css
  src/components/faststore-components/Tokens/token-colors.module.css
  src/components/faststore-components/Tokens/token-table.module.css
  src/components/faststore-components/Tokens/typeset.module.css
  src/components/faststore-components/faststore.module.css
  src/styles/documentation-page.ts
  src/styles/faststore.scss
  src/styles/global.css
Labels: release-patch

#649 feat(faststore/[slug].tsx): allow hideTOC frontmatter option
  src/components/faststore-components/SectionItem/section-item.module.css
  src/pages/docs/guides/faststore/[slug].tsx
Labels: release-no

#650 style(faststore.scss): update faststore table styles
  src/components/faststore-components/OverviewSection/OverviewSection.tsx
  src/components/last-updates-section/index.tsx
  src/styles/faststore.scss
  src/styles/global.css
Labels: release-no

#651 Feat/faststore productgridusage
  src/components/faststore-components/CardList/CardItem.tsx
  src/components/faststore-components/CardList/card-list.module.css
  src/components/faststore-components/ProductGrid/ProductGridUsage.tsx
  src/components/faststore-components/SectionItem/SectionItem.tsx
  src/components/faststore-components/SectionItem/section-item.module.css
  src/components/faststore-components/index.ts
  src/components/icons/arrow-right-icon.tsx
  src/styles/documentation-page.ts
  src/styles/faststore.scss
  src/styles/global.css
Labels: release-no

#652 style(sectionitem): update sectionitem styles
  src/components/faststore-components/SectionItem/SectionItem.tsx
  src/components/faststore-components/SectionItem/section-item.module.css
  src/styles/documentation-page.ts
  src/styles/global.css
Labels: release-no

#653 chore(package.json): update vtexdocs/components version
  package.json
  src/styles/apps-page.ts
Labels: release-no

#654 Update navigation.json
  public/navigation.json
Labels: release-no

#655 docs(redirect): data protection plus
  netlify.toml
Labels: release-no

#657 docs: update redirect and navigation for store framework category
  netlify.toml
  public/navigation.json
Labels: release-no

#658 docs(navigation): fix copy sku files endpoint nav
  public/navigation.json
Labels: release-no

#662 Update navigation.json
  public/navigation.json
Labels: release-no

#663 fix: updating pick and pack api
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: documentation, release-no

#665 EDU-9997 - Creating redirect vtex.search/banner
  netlify.toml
Labels: release-no

#667 docs: remove data-privacy redirect
  netlify.toml
Labels: release-no

#664 feat(storefront-development): update storefront-developemnt page with…
  src/components/overview-section/index.tsx
  src/pages/docs/storefront-development/index.tsx
Labels: release-no

#666 docs(navigation): fix checkout security subcategory
  public/navigation.json
Labels: release-no
