Repository vtexdocs/devportal, pull requests merged in 2024-01, with the labels that each got.

#555 Fix: Reviews and Ratings API navbar links
  public/navigation.json
Labels: release-no

#557 Redirect dev portal legacy pages
  netlify.toml
Labels: release-patch

#558 docs(netlify.toml): redirect headless commerce release note
  netlify.toml
Labels: release-patch

#560 Update netlify.toml: Fixing docs redirects
  netlify.toml
Labels: release-no

#561 Update netlify.toml
  netlify.toml
Labels: release-no

#559 fix(faststore/[slug].tsx): allows listing faststore docs
  src/pages/docs/guides/faststore/[slug].tsx
  src/pages/docs/guides/faststore/index.tsx
Labels: release-auto

#562 fix(apps): edit specifiedVersion checks
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
Labels: release-no

#565 chore(faststore-componentes): update faststore components and constants
  src/components/faststore-components/Accordion/UsageAccordion.tsx
  src/components/faststore-components/Accordion/UsageAccordionMultiple.tsx
  src/components/faststore-components/CardList/CardItem.tsx
  src/components/faststore-components/CardList/CardList.tsx
  src/components/faststore-components/CardList/card-list.module.css
  src/components/faststore-components/Carousel/CarouselSimpleUsage.tsx
  src/components/faststore-components/Carousel/carousel-item.module.css
  src/components/faststore-components/constants.tsx
  src/components/faststore-components/index.ts
Labels: release-no

#567 Update navigation.json
  public/navigation.json
Labels: release-no

#566 Docs: update container-template.json
  public/container-template.json
Labels: release-no

#568 style(faststore-components): improve faststore content rendering styles
  src/components/faststore-components/CardList/card-list.module.css
  src/components/faststore-components/SectionItem/SectionItem.tsx
  src/components/faststore-components/SectionItem/section-item.module.css
  src/components/faststore-components/Tokens/token-table.module.css
  src/components/faststore-components/Tokens/typeset.module.css
  src/components/faststore-components/markdown-renderer/fastStoreComponents.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/faststore/[slug].tsx
  src/styles/documentation-page.ts
Labels: release-no

#569 Update navigation.json
  public/navigation.json
Labels: release-no

#570 chore(package.json): update components lib version
  package.json
  src/components/faststore-components/markdown-renderer/fastStoreComponentsStyle.ts
  src/styles/documentation-page.ts
Labels: release-auto

#571 feat(faststore/[slug].tsx): enable seeAlso functionality
  src/pages/docs/guides/faststore/[slug].tsx
Labels: release-patch

#556 Update navigation.json
  public/navigation.json
Labels: release-no

#573 Fix: Documentation guidelines slug in navigation.json
  public/navigation.json
Labels: release-no

#574 docs(navigation): fix master data api v1 and v2 navigation
  public/navigation.json
Labels: release-no

#572 docs(navigation): edit store framework navigation
  public/navigation.json
Labels: release-no

#576 chore(getfaststorepaths): update FastStore docs branch
  src/pages/docs/guides/faststore/[slug].tsx
  src/utils/getDocsPaths.ts
  src/utils/getFastStorePaths.ts
Labels: release-no

#575 Update netlify.toml: Fixing doc redirect
  netlify.toml
Labels: release-no

#578 Redirect VTEX Tracking
  netlify.toml
Labels: release-no

#579 Chore/update faststore package version
  package.json
  src/components/faststore-components/CartSidebar/CartSidebarUsage.tsx
  src/components/faststore-components/Gift/GiftTemplate.tsx
  src/components/faststore-components/Gift/GiftTemplateIcon.tsx
  src/components/faststore-components/Gift/GiftTemplateWithoutBadge.tsx
  src/components/faststore-components/Navigation/NavbarLinksUsage.tsx
  src/components/faststore-components/Navigation/NavbarSliderUsage.tsx
  src/components/faststore-components/Navigation/NavbarUsage.tsx
  src/components/faststore-components/Newsletter/NewsletterUsage.tsx
  src/components/faststore-components/Rating/RatingActionable.tsx
  src/components/faststore-components/RegionBar/RegionBarEditUsage.tsx
  src/components/faststore-components/RegionBar/RegionBarUsage.tsx
  src/components/faststore-components/SectionItem/SectionItem.tsx
  src/components/faststore-components/Table/UsageTableBordered.tsx
  src/components/faststore-components/Table/UsageTableColored.tsx
  src/components/faststore-components/Table/UsageTableExample.tsx
  src/components/faststore-components/constants.tsx
  src/components/faststore-components/index.ts
Labels: release-patch
