Repository vtexdocs/devportal, pull requests merged in 2025-04, with the labels that each got.

#922 remove ad network api
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/pages/api/postman/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#924 docs(navigation): remove deprecated guide
  public/navigation.json
Labels: release-no

#925 docs(navigation.json): remove FastStore and Ad Network integration guide
  public/navigation.json
Labels: release-no

#927 docs(navigation.json): Add 'Sending custom events' guide
  public/navigation.json
Labels: release-no

#917 Edu 13288 Redirect link
  netlify.toml
Labels: release-no

#929 docs(navigation.json): add FastStore Cart overview
  public/navigation.json
Labels: release-no

#932 chore(modalbase.tsx): add ModalFooter to FastStore Modal usage example
  src/components/faststore-components/Modal/ModalBase.tsx
Labels: release-no

#933 feat(api): improve OpenAPI spec delivery with tiered caching strategy
  src/pages/api/openapi/[slug].tsx
  src/pages/docs/api-reference/[slug].tsx
Labels: release-minor

#934 refactor(api): update getReferencePaths to use internal API routes
  src/pages/api/openapi/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#935 Fix OpenAPI spec reference resolution in API reference documentation
  src/pages/api/openapi/[slug].tsx
  src/pages/docs/api-reference/[slug].tsx
Labels: release-patch

#936 fix(api): correct SwaggerParser options for handling circular references
  src/pages/api/openapi/[slug].tsx
  src/pages/docs/api-reference/[slug].tsx
Labels: release-patch

#937 Feat/netlify caching improvements
  README.md
  src/pages/api/openapi/[slug].tsx
Labels: release-no

#938 Auth performance improvements
  ARCHITECTURE.md
  src/components/auth/index.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].js
  src/pages/api/preview.ts
  src/utils/contexts/auth.tsx
Labels: release-no

#940 docs: remove Conversational Commerce from navigation
  public/navigation.json
Labels: release-no

#944 EDU-8800 feat: update netlify.toml / add redirect
  netlify.toml
Labels: bug, release-patch

#942 Docs/EDU-14697-FastStore WebOps: Improved the integration with the Headless CMS
  public/navigation.json
Labels: release-no

#946 docs/EDU-14653-Release-note-Feature/height-siteeditor
  public/navigation.json
Labels: release-no

#945 feat: add delivery promise api
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/pages/api/postman/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: enhancement, release-patch

#947 fix(getreferencepaths): fix prettier issues
  src/pages/api/openapi/[slug].tsx
  src/pages/api/postman/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: release-no

#948 EDU-14815 feat: add delivery promise api release note
  public/navigation.json
Labels: enhancement, release-patch

#950 Changing navigation Delete category from subcollection endpoint path
  public/navigation.json
Labels: release-no

#943 docs/EDU-14918 - RatingField
  public/navigation.json
Labels: release-no

#931 Docs/EDU-13537 - Cross-border
  netlify.toml
  public/navigation.json
Labels: release-no

#930 docs(navigation.json): add `useCart` guide
  public/navigation.json
Labels: release-no

#955 docs(navigation.json): add FastStore GraphQL cache control guide
  public/navigation.json
Labels: release-no

#954 docs(navigation.json): add new FastStore release note
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no
