Repository vtexdocs/devportal, pull requests merged in 2025-09, with the labels that each got.

#1000 docs(navigation.json): FastStore new categories
  netlify.toml
  public/navigation.json
Labels: release-no

#1041 feat: add delivery promise doc
  public/navigation.json
Labels: documentation, release-patch

#1043 style(breadcrumb): fix icon colors and breadcrumb wrapping
  src/components/breadcrumb/index.tsx
  src/components/breadcrumb/styles.ts
  src/components/icons/arrow-right-icon.tsx
  src/components/icons/github-icon.tsx
  src/pages/docs/apps/[slug]/[child].tsx
  src/pages/docs/apps/[slug]/index.tsx
  src/pages/docs/guides/[slug].tsx
  src/pages/docs/guides/faststore/[slug].tsx
  src/pages/docs/storefront-development/index.tsx
  src/pages/docs/troubleshooting/[slug].tsx
  src/styles/documentation-landing-page.ts
Labels: release-auto

#1046 feat(package.json): install fontawesome
  package.json
  src/pages/_app.tsx
  src/styles/global.css
Labels: release-no

#1049 EDU-15167 Added new sidebar
  public/navigation.json
Labels: release-no

#1050 chore(package.json): update @vtexdocs/components
  package.json
  src/pages/server-sitemap.xml/index.ts
  src/utils/navigation-utils.ts
Labels: release-auto

#1054 chore(algolia): update scraper for compatibility with components package
  algolia/scraper_md.json
  algolia/scraper_openapi.json
Labels: release-no

#1055 chore(_app.tsx): update metadata
  src/pages/_app.tsx
Labels: release-no

#1057 Update navigation.json
  public/navigation.json
Labels: release-no

#1058 Update navigation.json
  public/navigation.json
Labels: release-no
