Repository vtexdocs/devportal, pull requests merged in 2025-01, with the labels that each got.

#852 Update netlify.toml
  netlify.toml
Labels: release-no

#853 Update navigation.json
  public/navigation.json
Labels: release-no

#854 add(navigation.json): 2025 release note category
  public/navigation.json
Labels: release-no

#850 EDU-13472: Update navigation.json
  public/navigation.json
Labels: release-no

#856 EDU-13833: Release note (Update navigation.json)
  public/navigation.json
Labels: release-no

#857 EDU-13945 Redirect links
  netlify.toml
Labels: release-no

#858 docs: create redirect
  netlify.toml
Labels: release-no

#859 docs(navigation.json): adding doc to sidebar
  public/navigation.json
Labels: release-no

#862 Update 'last-updates-card' index.tsx
  src/components/last-updates-section/index.tsx
Labels: release-no

#860 docs(navigation.json): adding advanced layout docs to sidebar
  public/navigation.json
Labels: release-no

#864 Docs/edu 13880 404 page
  public/navigation.json
Labels: release-no

#863 EDU-14195 (navigation.json): Update FastStore go live steps
  netlify.toml
  public/navigation.json
Labels: release-no

#866 docs: create redirect for architecture guide
  netlify.toml
Labels: release-no

#867 Docs/Configuring Analytics on Store Framework
  netlify.toml
  public/navigation.json
Labels: release-no

#764 docs(navigation.json): storefront best practices
  netlify.toml
  public/navigation.json
Labels: release-no

#868 docs(netlify.toml): performance
  netlify.toml
Labels: release-no

#855 Category cover: Managing performance
  netlify.toml
  public/navigation.json
Labels: release-no

#869 [EDU-13992] feat: add pick and pack order changes api
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/pages/api/postman/[slug].tsx
  src/utils/getReferencePaths.ts
Labels: documentation, release-patch

#871 chore(api-reference): update the position in the sidebar when an api-…
  src/pages/docs/api-reference/[slug].tsx
Labels: release-patch

#872 Fix/hash links behavior apis
  src/pages/docs/api-reference/[slug].tsx
Labels: release-no

#873 docs(netlify.toml): SEO
  netlify.toml
Labels: release-no

#870 docs(navigation): add ad network integration endpoints
  public/navigation.json
Labels: release-no
