Repository vtexdocs/devportal, pull requests merged in 2025-03, with the labels that each got.

#892 feat(dockerfile): add dockerfile for running devmode
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  yarn.lock
Labels: release-minor

#893 fix(openreplay): remove openreplay tracker
  package.json
  src/components/layout.tsx
  src/pages/_app.tsx
  src/utils/contexts/trackerContext.tsx
  yarn.lock
Labels: release-patch

#874 docs(navigation): add payment notification endpoints
  public/navigation.json
Labels: release-no

#896 Fix sidebar
  public/navigation.json
Labels: release-no

#890 docs(navigation.json): add b2b quotes graphql
  public/navigation.json
Labels: documentation, release-no

#898 feat(navigation.json): New FastStore SEO docs
  public/navigation.json
Labels: release-no

#897 feat(navigation.json): add FastStore release note (EDU14349)
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#900 feat(index.tsx): update 'last-updates-section'
  src/components/last-updates-section/index.tsx
Labels: release-no

#904 docs(navigation.json): move apps troubleshooting
  public/navigation.json
Labels: documentation, release-no

#906 Update navigation.json
  public/navigation.json
Labels: release-no

#908 EDU-12149 Redirect link Pricing API
  netlify.toml
Labels: release-no

#909 feat(navigation.json): add new FastStore guide
  public/navigation.json
Labels: release-no

#910 feat(navigation.json): add FastStore Search guides
  public/navigation.json
Labels: release-no

#911 docs(navigation.json): add Messages app doc and API reference
  public/navigation.json
Labels: documentation, release-no

#907 docs(navigation): add vtex id release notes
  public/navigation.json
Labels: release-no

#912 docs: document github actions and its dependencies
  README.md
Labels: release-no

#914 EDU-14557-Added release notes to sidebar
  public/navigation.json
Labels: release-no

#913 EDU-14660 added endpoint to sidebar
  public/navigation.json
Labels: release-no

#915 EDU-14390 feat: add Operational Capacity API to navigation
  public/navigation.json
  src/pages/api/openapi/[slug].tsx
  src/pages/api/postman/[slug].tsx
Labels: enhancement, release-patch

#916 feat(navigation.json): update FastStore SEO category and fix docs redirects
  netlify.toml
  public/navigation.json
Labels: release-no

#918 EDU-14390-add-Operational-Capacity-API
  src/utils/getReferencePaths.ts
Labels: enhancement, release-patch

#919 EDU-14390-add-Operational-Capacity-API
  public/navigation.json
Labels: bug, release-patch

#920 feat(navigation.json): EDU-14516 - Add Session guide
  public/navigation.json
Labels: release-no

#921 feat: add operational capacity api release note to navigation
  public/navigation.json
Labels: enhancement, release-patch
