Repository vtexdocs/devportal, pull requests merged in 2025-05, with the labels that each got.

#957 docs(navigation.json): Release note - FastStore: Improved breadcrumb navigation
  public/navigation.json
Labels: release-no

#958 docs(navigation.json): add new sdk doc
  public/navigation.json
Labels: release-no

#956 docs(navigation.json): add section cover "graphql in vtex io"
  public/navigation.json
Labels: documentation, release-no

#961 Update navigation.json
  public/navigation.json
Labels: release-no

#960 docs(navigation.json): fix guide slug
  public/navigation.json
Labels: release-no

#962 feat: add new affiliate endpoints
  public/navigation.json
Labels: documentation, enhancement, release-patch

#966 chore(apps/[slug]/[child].tsx): add remarkMermaid
  src/pages/docs/apps/[slug]/[child].tsx
Labels: release-no

#967 docs(navigation.json): my account faststore
  public/navigation.json
Labels: release-no

#952 docs(navigation.json): EDU-14484 - adding `Tooltip` to the sidebar
  public/navigation.json
Labels: release-no

#964 docs(navigation.json): adding `Textarea` and `TextareaField` to sidebar
  public/navigation.json
Labels: release-no

#970 EDU-11170 - Fix 404
  netlify.toml
Labels: release-no

#971 docs(navigation.json): removing my account docs from sidebar
  public/navigation.json
Labels: release-no

#949 docs/EDU-14333 - Store Framework glossary
  public/navigation.json
Labels: release-no

#972 docs(navigation.json): FastStore new release note (SEO flags)
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#973 EDU 11170 - Fix URL for redirect
  netlify.toml
Labels: release-no

#975 docs(navigation.json): Validating UTM tracking
  public/navigation.json
Labels: release-no

#976 EDU-11170 - Fix origin's URL
  netlify.toml
Labels: documentation, release-no

#977 docs(navigation.json): Release note: new experimental flag'graphqlCacheControl
  public/navigation.json
  src/components/last-updates-section/index.tsx
Labels: release-no

#974 EDU-15072 redirect document
  netlify.toml
Labels: release-no

#980 fix: ssl-certificates-api navigation
  public/navigation.json
Labels: release-no

#981 feat(PopoverUsage.tsx): adding popover usage example
  package.json
  src/components/faststore-components/Popover/PopoverUsage.tsx
  src/components/faststore-components/index.ts
Labels: release-no
